---
- name: Download plugin {{ item }}
  get_url:
    url: "{{ sonar_plugins[item].url }}"
    checksum: "sha256:{{ sonar_plugins[item].checksum }}"
    dest: "{{sonar_home}}/{{ sonar_version_directory }}/extensions/plugins"
    group: sonarqube
    owner: sonarqube    
  with_items: "{{ sonar_plugins }}"